name: General Restore and Build

on:
  push:
    branches: [ "dev", "prod" ]
  pull_request:
    branches: [ "dev", "prod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore backend dependencies
      run: |
            cd backend
            dotnet restore 
    - name: Build backend dependencies 
      run: |
            cd backend
            dotnet build
    
    - name: Build frontend dependencies
      run: |
            cd frontend/TodoApp
            ng build