# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check general frontend dependencies

on:
  push:
    branches: [ "dev", "production" ]
  pull_request:
    branches: [ "dev", "production" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build frontend dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: |
            cd frontend/TodoApp
            npm install -g @angular/cli
            npm install 
            npm run build 
